### ISSUE TITLE
How to install the module under the Windows 7?

### ISSUE THREAD

**Issue by VooVoo01** [h0x91b/redis-fast-driver#10]
Is it possible to install the module under the Windows 7?
I've tried to do it (with installed Python 3.5.2, 2.7.12 and 2.7.11) but there some understandable errors and warnings during compiling module. For example:
....\deps\hiredis\net.c(35): fatal error C1083: Can't open file: sys/socket.h: No such file or directory [node_modules\redis-fast-driver\build\deps\hiredis.vcxproj]
....\deps\hiredis\async.c(35): fatal error C1083: Can't open file: strings.h: No such file or directory [node_modules\redis-fast-driver\build\deps\hiredis.vcxproj]
....\deps\hiredis\hiredis.c(35): fatal error C1083: Can't open file: unistd.h: No such file or directory [no 
de_modules\redis-fast-driver\build\deps\hiredis.vcxproj]
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: __pfnDliNotifyHook2: override; different type modifiers [node_modules\redis-fast-driver\build\deps\hiredis.vcxproj]

**Comment by h0x91b** [comment]
No this module is designed only for UNIX like OS's.

I can do some emulator for windows with same API for developers, but it will work very slowly on windows.

**Comment by VooVoo01** [comment]
I've installed it on Linux Debian without any errors and all seems right. But there is other problem, what does it mean? I work with root permeation.
_module.js:583
  return process.dlopen(module, path._makeLong(filename));
                 ^
Error: .../node_modules/redis-fast-driver/build/Release/redis-fast-driver.node: failed to map segment from shared object: Operation not permitted_

**Comment by h0x91b** [comment]
Have no idea what is it, maybe check if during installation some warnings appears?
