### ISSUE TITLE
[HELP] cannot await redis.rawCallAsync(['UNSUBSCRIBE'])

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [h0x91b/redis-fast-driver#16]
Hi,

The following function never passes by the `rawCallAsync` invocation. No idea why. @h0x91b, I need help.

```
async stop() {
  await this.listener.rawCallAsync(['UNSUBSCRIBE']);
  return await stop(this.listener);
}

```

**Comment by h0x91b** [comment]
Ok, I will debug this, probably issue on C side.

**Comment by h0x91b** [comment]
Sorry, I can not fix it. When I run unsubscribe the `hiredis` doesn't call the unsubscribe callback, instead, he calls previous callback but with different `type`. This is by design of hiredis...

	let once = false
	r.rawCall(['subscribe', 'foo'], (e, [type, channel, msg]) => {
		// type will be "message" or "unsubscribe"
		console.log('on channel foo e=%s type=%s channel=%s msg=%s', e, type, channel, msg)
		if(!once) {
			once = true
			r.rawCall(['unsubscribe'], function(){
				console.log('this callback is never called by hiredis')
			})
		}
	});
