### ISSUE TITLE
 PUB/SUB not working as expected.

### ISSUE THREAD

**Issue by tarangill** [h0x91b/redis-fast-driver#30]
When subscribed to a channel, no events are emitted when something is published on that channel. The subscriber does not get notified on a message.

Even in your pub/sub example, the subscriber just subscribes to a channel "Foo", and when the publisher publishes to channel "Foo", the subscriber does not get notified.

**Comment by tarangill** [comment]
Actually the callback of the Subscriber rawCall is called everytime somebody publishes a message to that channel. I don't know if that is the intended purpose, but it solves my issue.

**Comment by h0x91b** [comment]
Yes, it's by design, use your callback.

https://github.com/h0x91b/redis-fast-driver/blob/master/example-pubsub.js
