### ISSUE TITLE
redis error Error: ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context

### ISSUE THREAD

**Issue by sirganya** [h0x91b/redis-fast-driver#32]
I wanted to write a test to publish and subscribe to the same channel. What's the best way to get around this error?

**Comment by h0x91b** [comment]
You must use separate Redis clients, a subscription is a special mode, you can not use regular commands when a client in this mode...

check: https://github.com/h0x91b/redis-fast-driver/blob/master/example-pubsub.js
