### ISSUE TITLE
Callback for unsubscribe

### ISSUE THREAD

**Issue by sirganya** [h0x91b/redis-fast-driver#33]
When I execute 

```javascript
redis.rawcall([ 'unsubscribe', 'myChannel' ], (err, res) => {
    console.log(res);
});
```
The callback is not executed. Is this the expected behaviour?

**Comment by h0x91b** [comment]
Sorry for the late response, it doesn't

![Screen Shot 2021-09-23 at 13 44 20](https://user-images.githubusercontent.com/810011/134494177-b65b53b9-7bf7-4690-aea4-69e99dd3e8dd.jpg)
