### ISSUE TITLE
Redis 6

### ISSUE THREAD

**Issue by sirganya** [h0x91b/redis-fast-driver#39]
Is Redis 6 supported?

**Comment by h0x91b** [comment]
Nope

**Comment by sirganya** [comment]
Is it on the roadmap or have you moved on from this project?

**Comment by h0x91b** [comment]
Not at this moment, I am don't have free time at all last year :(

If I'll have a time then I will rewrite this module to N-API and then will add support to redis 6 as well.

Best Regards,
Arseny

**Comment by h0x91b** [comment]
Redis 6 SSL isn't supported, but regular non-SSL works well... Tested on Redis 6.0.9
