### ISSUE TITLE
Question: how to select database

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [h0x91b/redis-fast-driver#4]
Is there a way to specify which database to connect to?

Thank you!

**Comment by h0x91b** [comment]
Hi Dmitry, 

Sorry, didn't saw your question.

I will implement auth & db selection via ```ops```, currently you can use ```r.rawCall(['auth', 'topsecretpasssord']);``` for authentication and
```r.rawCall(['select', 16]);``` for DB selections as a workaround.

**Comment by Dmitry-N-Medvedev** [comment]
Thank you! :)

PS this is not a workaround, this is exactly as it should be.

**Comment by wwindcloud** [comment]
How about if you get disconnected, looking at the code, if it reconnects, it will just make it to the default db only. Doing select on connect callback is not ok since you are clearing the queue before invoking "connect" event.

Thanks.

**Comment by h0x91b** [comment]
agree I'll add DB selection option to config

**Comment by h0x91b** [comment]
I added pull request #9 , what do you think guys, merge it?

**Comment by wwindcloud** [comment]
Am I seeing it wrong, you are queuing "SELECT" only if opts.auth is not undefined? Thanks.

**Comment by h0x91b** [comment]
@wwindcloud thanks for code review, you are right again :) please check a fresh code in #9

**Comment by wwindcloud** [comment]
Looks fine but I am not sure if it's ok to continue when there's an error after the "SELECT" operation, might be a reconnect() after emit would be better.

**Comment by h0x91b** [comment]
@wwindcloud ok, done
