### ISSUE TITLE
Old module version

### ISSUE THREAD

**Issue by apeman76** [h0x91b/redis-fast-driver#49]
Im currently running Node 14.17.5 which works fine, but when updating to 16.13.0 I get a error about redis-fast-driver using a old module version:
```
Error: The module '/node_modules/redis-fast-driver/build/Release/redis-fast-driver.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

**Comment by h0x91b-wix** [comment]
Hi, after upgrading NodeJS you must remove `node_modules` and re-install it.

Checked on v16.13.0 works just fine for me...
